/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as JinisRouteImport } from './routes/jinis'
import { Route as JinischaraRouteImport } from './routes/jinischara'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDailyCalculationRouteImport } from './routes/admin/daily-calculation'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as AdminInterestRouteImport } from './routes/admin/interest'
import { Route as AdminMainCalculationRouteImport } from './routes/admin/main-calculation'
import { Route as AdminMigrationRouteImport } from './routes/admin/migration'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as JinisIndexRouteImport } from './routes/jinis/index'
import { Route as JinisNewRouteImport } from './routes/jinis/new'
import { Route as JinischaraIndexRouteImport } from './routes/jinischara/index'
import { Route as AdminDailyCalculationIndexRouteImport } from './routes/admin/daily-calculation/index'
import { Route as AdminMainCalculationIndexRouteImport } from './routes/admin/main-calculation/index'
import { Route as AdminMigrationIndexRouteImport } from './routes/admin/migration/index'
import { Route as AdminMigrationJinischaraRouteImport } from './routes/admin/migration/jinischara'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminDailyCalculationIdDetailRouteImport } from './routes/admin/daily-calculation/$id/detail'
import { Route as AdminMainCalculationIdDetailRouteImport } from './routes/admin/main-calculation/$id/detail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const JinisRoute = JinisRouteImport.update({
  id: '/jinis',
  path: '/jinis',
  getParentRoute: () => rootRouteImport,
} as any)
const JinischaraRoute = JinischaraRouteImport.update({
  id: '/jinischara',
  path: '/jinischara',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyCalculationRoute = AdminDailyCalculationRouteImport.update({
  id: '/daily-calculation',
  path: '/daily-calculation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterestRoute = AdminInterestRouteImport.update({
  id: '/interest',
  path: '/interest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMainCalculationRoute = AdminMainCalculationRouteImport.update({
  id: '/main-calculation',
  path: '/main-calculation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const JinisIndexRoute = JinisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JinisRoute,
} as any)
const JinisNewRoute = JinisNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JinisRoute,
} as any)
const JinischaraIndexRoute = JinischaraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JinischaraRoute,
} as any)
const AdminDailyCalculationIndexRoute =
  AdminDailyCalculationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDailyCalculationRoute,
  } as any)
const AdminMainCalculationIndexRoute =
  AdminMainCalculationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMainCalculationRoute,
  } as any)
const AdminMigrationIndexRoute = AdminMigrationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMigrationRoute,
} as any)
const AdminMigrationJinischaraRoute =
  AdminMigrationJinischaraRouteImport.update({
    id: '/jinischara',
    path: '/jinischara',
    getParentRoute: () => AdminMigrationRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDailyCalculationIdDetailRoute =
  AdminDailyCalculationIdDetailRouteImport.update({
    id: '/$id/detail',
    path: '/$id/detail',
    getParentRoute: () => AdminDailyCalculationRoute,
  } as any)
const AdminMainCalculationIdDetailRoute =
  AdminMainCalculationIdDetailRouteImport.update({
    id: '/$id/detail',
    path: '/$id/detail',
    getParentRoute: () => AdminMainCalculationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/jinis': typeof JinisRouteWithChildren
  '/jinischara': typeof JinischaraRouteWithChildren
  '/signin': typeof SigninRoute
  '/admin/daily-calculation': typeof AdminDailyCalculationRouteWithChildren
  '/admin/export': typeof AdminExportRoute
  '/admin/interest': typeof AdminInterestRoute
  '/admin/main-calculation': typeof AdminMainCalculationRouteWithChildren
  '/admin/migration': typeof AdminMigrationRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/jinis/new': typeof JinisNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jinis/': typeof JinisIndexRoute
  '/jinischara/': typeof JinischaraIndexRoute
  '/admin/migration/jinischara': typeof AdminMigrationJinischaraRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/daily-calculation/': typeof AdminDailyCalculationIndexRoute
  '/admin/main-calculation/': typeof AdminMainCalculationIndexRoute
  '/admin/migration/': typeof AdminMigrationIndexRoute
  '/admin/daily-calculation/$id/detail': typeof AdminDailyCalculationIdDetailRoute
  '/admin/main-calculation/$id/detail': typeof AdminMainCalculationIdDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/interest': typeof AdminInterestRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/jinis/new': typeof JinisNewRoute
  '/admin': typeof AdminIndexRoute
  '/jinis': typeof JinisIndexRoute
  '/jinischara': typeof JinischaraIndexRoute
  '/admin/migration/jinischara': typeof AdminMigrationJinischaraRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/daily-calculation': typeof AdminDailyCalculationIndexRoute
  '/admin/main-calculation': typeof AdminMainCalculationIndexRoute
  '/admin/migration': typeof AdminMigrationIndexRoute
  '/admin/daily-calculation/$id/detail': typeof AdminDailyCalculationIdDetailRoute
  '/admin/main-calculation/$id/detail': typeof AdminMainCalculationIdDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/jinis': typeof JinisRouteWithChildren
  '/jinischara': typeof JinischaraRouteWithChildren
  '/signin': typeof SigninRoute
  '/admin/daily-calculation': typeof AdminDailyCalculationRouteWithChildren
  '/admin/export': typeof AdminExportRoute
  '/admin/interest': typeof AdminInterestRoute
  '/admin/main-calculation': typeof AdminMainCalculationRouteWithChildren
  '/admin/migration': typeof AdminMigrationRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/jinis/new': typeof JinisNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jinis/': typeof JinisIndexRoute
  '/jinischara/': typeof JinischaraIndexRoute
  '/admin/migration/jinischara': typeof AdminMigrationJinischaraRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/daily-calculation/': typeof AdminDailyCalculationIndexRoute
  '/admin/main-calculation/': typeof AdminMainCalculationIndexRoute
  '/admin/migration/': typeof AdminMigrationIndexRoute
  '/admin/daily-calculation/$id/detail': typeof AdminDailyCalculationIdDetailRoute
  '/admin/main-calculation/$id/detail': typeof AdminMainCalculationIdDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/jinis'
    | '/jinischara'
    | '/signin'
    | '/admin/daily-calculation'
    | '/admin/export'
    | '/admin/interest'
    | '/admin/main-calculation'
    | '/admin/migration'
    | '/admin/sessions'
    | '/jinis/new'
    | '/admin/'
    | '/jinis/'
    | '/jinischara/'
    | '/admin/migration/jinischara'
    | '/api/auth/$'
    | '/admin/daily-calculation/'
    | '/admin/main-calculation/'
    | '/admin/migration/'
    | '/admin/daily-calculation/$id/detail'
    | '/admin/main-calculation/$id/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/admin/export'
    | '/admin/interest'
    | '/admin/sessions'
    | '/jinis/new'
    | '/admin'
    | '/jinis'
    | '/jinischara'
    | '/admin/migration/jinischara'
    | '/api/auth/$'
    | '/admin/daily-calculation'
    | '/admin/main-calculation'
    | '/admin/migration'
    | '/admin/daily-calculation/$id/detail'
    | '/admin/main-calculation/$id/detail'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/jinis'
    | '/jinischara'
    | '/signin'
    | '/admin/daily-calculation'
    | '/admin/export'
    | '/admin/interest'
    | '/admin/main-calculation'
    | '/admin/migration'
    | '/admin/sessions'
    | '/jinis/new'
    | '/admin/'
    | '/jinis/'
    | '/jinischara/'
    | '/admin/migration/jinischara'
    | '/api/auth/$'
    | '/admin/daily-calculation/'
    | '/admin/main-calculation/'
    | '/admin/migration/'
    | '/admin/daily-calculation/$id/detail'
    | '/admin/main-calculation/$id/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  JinisRoute: typeof JinisRouteWithChildren
  JinischaraRoute: typeof JinischaraRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinis': {
      id: '/jinis'
      path: '/jinis'
      fullPath: '/jinis'
      preLoaderRoute: typeof JinisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinischara': {
      id: '/jinischara'
      path: '/jinischara'
      fullPath: '/jinischara'
      preLoaderRoute: typeof JinischaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily-calculation': {
      id: '/admin/daily-calculation'
      path: '/daily-calculation'
      fullPath: '/admin/daily-calculation'
      preLoaderRoute: typeof AdminDailyCalculationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interest': {
      id: '/admin/interest'
      path: '/interest'
      fullPath: '/admin/interest'
      preLoaderRoute: typeof AdminInterestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/main-calculation': {
      id: '/admin/main-calculation'
      path: '/main-calculation'
      fullPath: '/admin/main-calculation'
      preLoaderRoute: typeof AdminMainCalculationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jinis/': {
      id: '/jinis/'
      path: '/'
      fullPath: '/jinis/'
      preLoaderRoute: typeof JinisIndexRouteImport
      parentRoute: typeof JinisRoute
    }
    '/jinis/new': {
      id: '/jinis/new'
      path: '/new'
      fullPath: '/jinis/new'
      preLoaderRoute: typeof JinisNewRouteImport
      parentRoute: typeof JinisRoute
    }
    '/jinischara/': {
      id: '/jinischara/'
      path: '/'
      fullPath: '/jinischara/'
      preLoaderRoute: typeof JinischaraIndexRouteImport
      parentRoute: typeof JinischaraRoute
    }
    '/admin/daily-calculation/': {
      id: '/admin/daily-calculation/'
      path: '/'
      fullPath: '/admin/daily-calculation/'
      preLoaderRoute: typeof AdminDailyCalculationIndexRouteImport
      parentRoute: typeof AdminDailyCalculationRoute
    }
    '/admin/main-calculation/': {
      id: '/admin/main-calculation/'
      path: '/'
      fullPath: '/admin/main-calculation/'
      preLoaderRoute: typeof AdminMainCalculationIndexRouteImport
      parentRoute: typeof AdminMainCalculationRoute
    }
    '/admin/migration/': {
      id: '/admin/migration/'
      path: '/'
      fullPath: '/admin/migration/'
      preLoaderRoute: typeof AdminMigrationIndexRouteImport
      parentRoute: typeof AdminMigrationRoute
    }
    '/admin/migration/jinischara': {
      id: '/admin/migration/jinischara'
      path: '/jinischara'
      fullPath: '/admin/migration/jinischara'
      preLoaderRoute: typeof AdminMigrationJinischaraRouteImport
      parentRoute: typeof AdminMigrationRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/daily-calculation/$id/detail': {
      id: '/admin/daily-calculation/$id/detail'
      path: '/$id/detail'
      fullPath: '/admin/daily-calculation/$id/detail'
      preLoaderRoute: typeof AdminDailyCalculationIdDetailRouteImport
      parentRoute: typeof AdminDailyCalculationRoute
    }
    '/admin/main-calculation/$id/detail': {
      id: '/admin/main-calculation/$id/detail'
      path: '/$id/detail'
      fullPath: '/admin/main-calculation/$id/detail'
      preLoaderRoute: typeof AdminMainCalculationIdDetailRouteImport
      parentRoute: typeof AdminMainCalculationRoute
    }
  }
}

interface AdminDailyCalculationRouteChildren {
  AdminDailyCalculationIndexRoute: typeof AdminDailyCalculationIndexRoute
  AdminDailyCalculationIdDetailRoute: typeof AdminDailyCalculationIdDetailRoute
}

const AdminDailyCalculationRouteChildren: AdminDailyCalculationRouteChildren = {
  AdminDailyCalculationIndexRoute: AdminDailyCalculationIndexRoute,
  AdminDailyCalculationIdDetailRoute: AdminDailyCalculationIdDetailRoute,
}

const AdminDailyCalculationRouteWithChildren =
  AdminDailyCalculationRoute._addFileChildren(
    AdminDailyCalculationRouteChildren,
  )

interface AdminMainCalculationRouteChildren {
  AdminMainCalculationIndexRoute: typeof AdminMainCalculationIndexRoute
  AdminMainCalculationIdDetailRoute: typeof AdminMainCalculationIdDetailRoute
}

const AdminMainCalculationRouteChildren: AdminMainCalculationRouteChildren = {
  AdminMainCalculationIndexRoute: AdminMainCalculationIndexRoute,
  AdminMainCalculationIdDetailRoute: AdminMainCalculationIdDetailRoute,
}

const AdminMainCalculationRouteWithChildren =
  AdminMainCalculationRoute._addFileChildren(AdminMainCalculationRouteChildren)

interface AdminMigrationRouteChildren {
  AdminMigrationJinischaraRoute: typeof AdminMigrationJinischaraRoute
  AdminMigrationIndexRoute: typeof AdminMigrationIndexRoute
}

const AdminMigrationRouteChildren: AdminMigrationRouteChildren = {
  AdminMigrationJinischaraRoute: AdminMigrationJinischaraRoute,
  AdminMigrationIndexRoute: AdminMigrationIndexRoute,
}

const AdminMigrationRouteWithChildren = AdminMigrationRoute._addFileChildren(
  AdminMigrationRouteChildren,
)

interface AdminRouteChildren {
  AdminDailyCalculationRoute: typeof AdminDailyCalculationRouteWithChildren
  AdminExportRoute: typeof AdminExportRoute
  AdminInterestRoute: typeof AdminInterestRoute
  AdminMainCalculationRoute: typeof AdminMainCalculationRouteWithChildren
  AdminMigrationRoute: typeof AdminMigrationRouteWithChildren
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDailyCalculationRoute: AdminDailyCalculationRouteWithChildren,
  AdminExportRoute: AdminExportRoute,
  AdminInterestRoute: AdminInterestRoute,
  AdminMainCalculationRoute: AdminMainCalculationRouteWithChildren,
  AdminMigrationRoute: AdminMigrationRouteWithChildren,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JinisRouteChildren {
  JinisNewRoute: typeof JinisNewRoute
  JinisIndexRoute: typeof JinisIndexRoute
}

const JinisRouteChildren: JinisRouteChildren = {
  JinisNewRoute: JinisNewRoute,
  JinisIndexRoute: JinisIndexRoute,
}

const JinisRouteWithChildren = JinisRoute._addFileChildren(JinisRouteChildren)

interface JinischaraRouteChildren {
  JinischaraIndexRoute: typeof JinischaraIndexRoute
}

const JinischaraRouteChildren: JinischaraRouteChildren = {
  JinischaraIndexRoute: JinischaraIndexRoute,
}

const JinischaraRouteWithChildren = JinischaraRoute._addFileChildren(
  JinischaraRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  JinisRoute: JinisRouteWithChildren,
  JinischaraRoute: JinischaraRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
